### ISSUE TITLE
whipper-git pkgver() step errors

### ISSUE THREAD

**Issue by wararjey** [alexheretic/aurto#64]
Hello,
when trying to build whipper-git I am seeing these error messages in the log:

```
  Jul 17 08:33:22 monster update-aurto[131605]:   -> Erstelle Arbeitskopie des whipper git Repos...
  Jul 17 08:33:22 monster update-aurto[131605]: Klone nach 'whipper' ...
  Jul 17 08:33:22 monster update-aurto[131605]: Fertig.
  Jul 17 08:33:22 monster update-aurto[131605]: Zu neuem Branch 'makepkg' gewechselt
  Jul 17 08:33:22 monster update-aurto[131605]: ==> Beginne pkgver()...
  Jul 17 08:33:22 monster update-aurto[131605]: WARNING: The wheel package is not available.
  Jul 17 08:33:22 monster update-aurto[131605]: /usr/bin/python3: No module named pip
  Jul 17 08:33:22 monster update-aurto[131605]: Traceback (most recent call last):
  Jul 17 08:33:22 monster update-aurto[131605]:   File "/usr/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
  Jul 17 08:33:22 monster update-aurto[131605]:     subprocess.check_call(cmd)
  Jul 17 08:33:22 monster update-aurto[131605]:   File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
  --
```
 Originally, I thought the missing makedep for python-pip might be the cause for this.

However, when building manually in a clean chroot, the package builds normally....

Regards,

**Comment by alexheretic** [comment]
I'd have thought missing makedeps too. Try deleting your aurutils chroot
root and running aurutils directly to build it (aurto prints what aurutils
commands it runs).

**Comment by wararjey** [comment]
I just did that and re-created the root chroot. aurutils did not display any error messages. With the re-created chroot root I removed and re-added the whipper-git package to aurto. No error messages, either. I'll let the nightly update run and check the logs again tomorrow...

**Comment by wararjey** [comment]
Nightly -git update run shows the same error. messages. Strangely enough, it is only the whipper-git package that seems to have this. I guess it might have something to do with that package's pkgver() code, but I am not sure why the python call should be a problem there...

**Comment by AladW** [comment]
Possibly related: https://github.com/AladW/aurutils/issues/771
